### PR TITLE
Binutils 2.32 WIP buildscript

### PR DESCRIPTION
**Pull request by extrowerk**
The provided commands should be run before the configure stage. I have no idea how to accomplish that, any hints?

### CODE REVIEW

**Comment by berryamin** [comment]
> 
> 
> The provided commands should be run before the configure stage. I have no idea how to accomplish that, any hints?

you may copy / paste a package_patch() from lib.sh to your build.sh and tune there inside ?

**Comment by extrowerk** [comment]
I was so far unable to find out why `make install` doesn't installs anathing. I suspect maybe the makefile is broken. Will try to build an official release to compare the results.
In the meantime feel free to try to locate the problem.

**Comment by berryamin** [comment]
build / install / bundle  ok

**Comment by extrowerk** [comment]
> build / install / bundle ok

Oh man, did i really forgot the bundle phase? Oh my gosh, i was already knee deep in the makefile to find out why it doesn't install anything. EEEeh! Thanks!

**Comment by extrowerk** [comment]
Thank You.
I am almost done with the irl work, will continue the jurney after that.

**Pull request merged**
